version: "3.9"
services:
  spark-master:
    build: ./spark-cluster
    command: >
      /bin/bash -c "chmod 777 /start-spark.sh && /start-spark.sh"
    ports:
      - "9090:8080"
      - "7077:7077"
      - "8888:8888"
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    volumes:
      - ./scripts/data:/data
      - ./data_processing:/scripts
